version: 0.2

env:
  variables:
    VITE_API_URL: "https://simuladores-qa.ebc.edu.mx/api/"
    VITE_CONTENT_CDN: "https://simuladores-qa.ebc.edu.mx/"

phases:
  install:
    runtime-versions:
      nodejs: 22.14.0

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Successfully logged in to Amazon ECR"
      - export GIT_COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
  build:
    commands:
      - echo "Building Frontend..."
      - cd $CODEBUILD_SRC_DIR/frontend
      - docker build --build-arg VITE_API_URL="$VITE_API_URL" --build-arg VITE_CONTENT_CDN="$VITE_CONTENT_CDN" -t simuladores-frontend:build -f Dockerfile .

      - cd $CODEBUILD_SRC_DIR

      - echo "Building Backend..."
      - cd $CODEBUILD_SRC_DIR/backend
      - docker build -t simuladores-backend:build -f Dockerfile .

      - cd $CODEBUILD_SRC_DIR

  post_build:
    commands:
      - echo "Tagging images..."

      # Frontend
      - docker tag simuladores-frontend:build $REPOSITORY_URI:frontend-latest
      - docker tag simuladores-frontend:build $REPOSITORY_URI:frontend-$GIT_COMMIT_HASH

      # Backend
      - docker tag simuladores-backend:build $REPOSITORY_URI:backend-latest
      - docker tag simuladores-backend:build $REPOSITORY_URI:backend-$GIT_COMMIT_HASH

      - echo "Pushing images..."
      - docker push $REPOSITORY_URI:frontend-latest
      - docker push $REPOSITORY_URI:frontend-$GIT_COMMIT_HASH
      - docker push $REPOSITORY_URI:backend-latest
      - docker push $REPOSITORY_URI:backend-$GIT_COMMIT_HASH
